"""
Django settings for notes project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#-------------------------------------------------------------------------------
# PROJECT DIRECTORIES
#-------------------------------------------------------------------------------
BASE_DIR = \
    os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

FILES_DIR = os.path.join(BASE_DIR, 'files')

TEMPLATES_DIR = os.path.join(FILES_DIR, 'templates')

STATIC_DIR = os.path.join(FILES_DIR, 'static')

STATIC_ROOT = os.path.join(FILES_DIR, 'assets')

MEDIA_ROOT = os.path.join(FILES_DIR, 'media')

FIXTURES_ROOT = os.path.join(FILES_DIR, 'fixtures')

FIXTURE_DIRS = [FIXTURES_ROOT, ]

STATICFILES_DIRS = [STATIC_DIR, ]

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ir$v-4l836a2bz219jwd#h+0vrp0%4o7^4u6^-2@c%b$i&6lv)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ROOT_URLCONF = 'notes.urls'
BASE_URL = ''
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
ALLOWED_HOSTS = []

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'notes.apps.account',
    'notes.apps.note',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'notes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'notes.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

#------------------------------------------------------------------------------
# DATABASE SETTINGS
#------------------------------------------------------------------------------
# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'notes',
        'USER': 'postgres',
        'PASSWORD': 'silver',
        'HOST': '127.0.0.1',
        'PORT': '5432',
        }
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'


#-------------------------------------------------------------------------------
#  REST SETTINGS
#-------------------------------------------------------------------------------
REST_FRAMEWORK = {
                      
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    ),
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'PAGINATE_BY_PARAM' : 'page_size',
    'MAX_PAGE_SIZE': 300,
    'PAGE_SIZE': 12
}